
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongodb-data:/data/db

  mongo-ub:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongodb-user:/data/db

  spring-userbase:
    build:
      context: ./spring-ub/
      dockerfile: Dockerfile
    ports:
      - "9001:9001"

  spring-database:
    build:
      context: ./spring-db/
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

volumes:
  mongodb-data:
    driver: local

  mongodb-user:
    driver: local
